title: Flexa Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Front End API
      category: Cluster
    - name: Back End API
      category: Cluster
    - name: General Services
      category: Cluster
    - name: Discord API
      category: Cluster
    - name: Re-Route Connections
      category: Cluster
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#3e97d8"
  enableLastMod: true
  headerTextColor: black
  logo: /img/new-project-3-.png
  incidentPostsPerPage: 3
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Cluster
      closed: true
  description: ""
  enableCustomHTML: true
  useLargeHeaderDesign: false
